[package]
name = "Beth_Editor_GUI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18.1"
open = "5.0.0"
flate2 = { version = "1.0.28", features = ["zlib"] }
lazy_static = "1.4.0"